#ifndef ENUMS_H
#define ENUMS_H

enum COLOR {RED, ORANGE, YELLOW, GREEN, BLUE, INDIGO, VIOLET};

enum TOOL {PENCIL, ERASER, MOUSE, CIRCLE, TRIANGLE, RECTANGLE, HEXAGON, STAR};

enum ACTION {NONE, UNDO, REDO, ENLARGE, REDUCE, CLEAR};

#endif